version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/usr/src/app/data/
        env_file:
            - .env
