services:
    libro-client:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - data:/app/data/
            - ${PWD}/downloads:/app/downloads/
        env_file:
            - .env

volumes:
    data: